server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos 服务地址
    gateway:
      routes: # 网关路由配置
        - id: nacos-user-service # 路由的id, 可以自己定义, 但是要唯一
          uri: lb://user-service # 路由的目标地址
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/**
          filters:
            - AddRequestHeader=Truth,AddRequestHeader success!
        - id: nacos-order-service # order-service 的路由
          uri: lb://order-service # 路由的目标地址
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/order/**
      globalcors: #  全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被 拦截问题
        cors-configurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期

